WIP: anonymous pricing access
Based on [1], but this currently fails with:

  $ go test ./platformtests/aws/
  --- FAIL: TestGetDefaultInstanceClass (0.52s)
  		default_instance_class_test.go:75: MissingAuthenticationTokenException: Missing Authentication Token
  																			 																			status code: 400, request id: 06db5443-3215-11e9-868d-03fa49ec56be
  FAIL
  FAIL		github.com/openshift/installer/platformtests/aws				0.522s

[1]: https://github.com/aws/aws-sdk-go/issues/205#issuecomment-98875714